"""Stage C of the study (Steps 9-12) plus every figure, table and the written report.

Reads Results/study/*.json written by study.py; every source present is used:
    fake_kingston, fake_marrakesh  (Step 3 noise-model predictions)
    ibm_kingston,  ibm_marrakesh   (Stage B hardware, once collected)
"""
import csv
import json
import math
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
from scipy.optimize import minimize_scalar

import oracles as orc

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "Results" / "study"
FIG = ROOT / "Figures" / "study"

# ---------------------------------------------------------------------------- style
INK, INK2, MUTED, GRID, SURF = "#1b1b1a", "#52514e", "#8d8b84", "#e9e8e3", "#fcfcfb"
DEV_COLOR = {"kingston": "#2a78d6", "marrakesh": "#eb6834"}
VAR_COLOR = {"noancilla": "#4a3aa7", "vchain": "#1baf7a", "vchain_rtof": "#eda100"}
VAR_LABEL = {"noancilla": "No ancilla", "vchain": "V-chain (Toffoli)", "vchain_rtof": "V-chain (relative-phase)"}
TECH = ["none", "m3", "dd", "twirl", "trex", "zne", "all"]
TECH_LABEL = {"none": "None", "m3": "M3", "dd": "DD", "twirl": "Twirling", "trex": "TREX", "zne": "ZNE",
              "all": "All"}
TECH_COLOR = {"none": "#8d8b84", "m3": "#e34948", "dd": "#2a78d6", "twirl": "#1baf7a", "trex": "#eda100",
              "zne": "#e87ba4", "all": "#4a3aa7"}
SINGLE, DOUBLE = 3.5, 7.16

plt.rcParams.update({
    "font.family": "serif", "font.serif": ["STIXGeneral", "Times New Roman", "DejaVu Serif"],
    "mathtext.fontset": "stix", "font.size": 8, "axes.titlesize": 8.5, "axes.titleweight": "bold",
    "axes.labelsize": 8, "xtick.labelsize": 7, "ytick.labelsize": 7, "legend.fontsize": 6.8,
    "legend.frameon": False, "axes.spines.top": False, "axes.spines.right": False,
    "axes.edgecolor": INK2, "axes.linewidth": 0.6, "axes.labelcolor": INK, "text.color": INK,
    "xtick.color": INK2, "ytick.color": INK2, "xtick.major.width": 0.6, "ytick.major.width": 0.6,
    "xtick.major.size": 2.5, "ytick.major.size": 2.5, "axes.grid": True, "axes.grid.axis": "y",
    "grid.color": GRID, "grid.linewidth": 0.6, "axes.axisbelow": True, "lines.linewidth": 1.5,
    "lines.markersize": 4.5, "hatch.linewidth": 0.5, "hatch.color": "white", "figure.facecolor": "white",
    "savefig.bbox": "tight", "savefig.pad_inches": 0.03, "pdf.fonttype": 42, "legend.handlelength": 1.6,
})


def dev_of(source):
    return source.split("_", 1)[1]


def is_hw(source):
    return source.startswith("ibm_")


def src_label(source):
    return ("QPU " if is_hw(source) else "Model ") + dev_of(source).capitalize()


def src_style(source):
    """Same hue per device; noise-model predictions hatched/hollow, hardware solid."""
    c = DEV_COLOR[dev_of(source)]
    if is_hw(source):
        return {"color": c, "hatch": "", "mfc": c, "ls": "-", "alpha": 1.0}
    return {"color": c, "hatch": "//////", "mfc": "white", "ls": "--", "alpha": 0.55}


def panel(ax, letter, x=-0.12):
    ax.text(x, 1.02, f"({letter})", transform=ax.transAxes, fontsize=9, fontweight="bold", va="bottom")


def save_fig(fig, name):
    FIG.mkdir(parents=True, exist_ok=True)
    for ext in ("pdf", "png"):
        fig.savefig(FIG / f"{name}.{ext}", dpi=300)
    plt.close(fig)


def load(name):
    p = OUT / name
    return json.loads(p.read_text()) if p.exists() else None


def write_table(name, header, rows, caption, label, align=None):
    """CSV + LaTeX (booktabs). Returns markdown for the report."""
    with open(OUT / f"{name}.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(header)
        w.writerows(rows)

    def tex(x):
        return str(x).replace("_", r"\_").replace("±", r"$\pm$").replace("%", r"\%").replace("→", r"$\to$")

    align = align or "l" + "r" * (len(header) - 1)
    body = "\n".join(" & ".join(tex(c) for c in r) + r" \\" for r in rows)
    (OUT / f"{name}.tex").write_text(
        "% generated by Code/study_analysis.py\n\\begin{table}[t]\n\\centering\n\\small\n"
        f"\\caption{{{tex(caption)}}}\n\\label{{{label}}}\n\\begin{{tabular}}{{{align}}}\n\\toprule\n"
        + " & ".join(tex(h) for h in header) + " \\\\\n\\midrule\n" + body + "\n\\bottomrule\n\\end{tabular}\n"
        "\\end{table}\n")
    md = "| " + " | ".join(header) + " |\n|" + "---|" * len(header) + "\n"
    md += "\n".join("| " + " | ".join(str(c) for c in r) + " |" for r in rows)
    return f"**{caption}**\n\n{md}\n"


def f3(x):
    return "–" if x is None else f"{x:.3f}"


# ============================================================================ Stage A outputs
def stage_a(report):
    d1, d2 = load("step1_design.json"), load("step2_baseline.json")
    if d1:
        inst = d1["instances"]
        rows = [[k, v["n"], len(v["clauses"]), v["cnf"], ", ".join(v["solutions"]), v["n"],
                 v["n"] + len(v["clauses"])] for k, v in inst.items()]
        report.append("## Stage A — Design and verification\n\n### Step 1: circuit design\n")
        report.append(write_table("tab_instances", ["Instance", "Vars", "Clauses", "CNF", "Solutions (x_n…x_1)",
                                                    "Qubits Oracle A", "Qubits Oracle B"], rows,
                                  "K-SAT instances (exactly 3 satisfying assignments each)", "tab:instances",
                                  "lrrlllr"))
        rows = []
        for r in d1["rows"]:
            rows.append([r["circuit"], VAR_LABEL[r["variant"]], r["qubits"], r["ancillas"], r["cz_kingston"],
                         r["depth_kingston"], r["cz_marrakesh"], "yes" if r["verified"] else "NO"])
        report.append(write_table("tab_step1_circuits", ["Circuit (k=1)", "MCT construction", "Qubits", "Ancillas",
                                                         "CZ Kingston", "Depth Kingston", "CZ Marrakesh",
                                                         "P = theory"], rows,
                                  "Circuit table: two-qubit (CZ) gate count after transpilation "
                                  "(optimization level 3) for each multi-controlled-gate construction",
                                  "tab:circuits", "llrrrrrr"))
        fig_circuit_cost(d1)
        fig_circuit_diagrams(d1)
    if d2:
        rows = [[r["n"], r["k"], f"{r['p_theory']:.4f}", f"{r['p_mean']:.4f} ± {r['p_std']:.4f}",
                 f"{r['max_abs_dev']:.4f}", f"{100 * r['within_3sigma']:.1f}%", r["states"] * r["reps"],
                 f"{1e3 * r['sim_time_per_circuit_s']:.2f}"] for r in d2["rows"]]
        report.append("### Step 2: simulator baseline (Aer QASM)\n")
        report.append(write_table("tab_I_simulator", ["n", "k", "P theory", "P sim (mean ± sd)", "max |dev|",
                                                      "within 3σ", "runs", "time/circuit (ms)"], rows,
                                  "Table I: ideal QASM simulator against theory P = sin²((2k+1)θ), every marked "
                                  "state, 5 repetitions × 1000 shots", "tab:I", "rrrrrrrr"))
        fig_baseline(d2)


def fig_circuit_cost(d1):
    rows = d1["rows"]
    fig, (a, b) = plt.subplots(1, 2, figsize=(DOUBLE, 2.5), gridspec_kw={"width_ratios": [1.15, 1]})
    for v in orc.VARIANTS:
        rr = [r for r in rows if r["circuit"].startswith("Grover") and r["variant"] == v]
        ns, cz = [r["n_vars"] for r in rr], [r["cz_kingston"] for r in rr]
        a.semilogy(ns, cz, "o-", color=VAR_COLOR[v], label=VAR_LABEL[v], mec="white", mew=0.6)
        a.annotate(f"{cz[-1]}", (ns[-1], cz[-1]), xytext=(4, 0), textcoords="offset points", va="center",
                   fontsize=6.5, color=INK2)
    a.set(xlabel=r"Search qubits $n$", ylabel="CZ gates (one Grover iteration)", xticks=range(2, 11),
          xlim=(1.6, 10.9))
    a.grid(True, which="major", axis="both")
    a.legend(loc="upper left")
    panel(a, "a")
    labels = [c for c in dict.fromkeys(r["circuit"] for r in rows if not r["circuit"].startswith("Grover"))]
    w = 0.26
    for j, v in enumerate(orc.VARIANTS):
        ys = [next(r["cz_kingston"] for r in rows if r["circuit"] == c and r["variant"] == v) for c in labels]
        xs = [i + (j - 1) * w for i in range(len(labels))]
        b.bar(xs, ys, w * 0.92, color=VAR_COLOR[v], label=VAR_LABEL[v])
        for x, y in zip(xs, ys):
            b.text(x, y + 8, str(y), ha="center", va="bottom", fontsize=5.6, color=INK2, rotation=90)
    b.set_xticks(range(len(labels)))
    b.set_xticklabels([c.replace(" Oracle ", "\nOracle ") for c in labels])
    b.set(ylabel="CZ gates (k = 1)", ylim=(0, max(r["cz_kingston"] for r in rows
                                                  if r["circuit"] in labels) * 1.28))
    panel(b, "b")
    fig.tight_layout(w_pad=2)
    save_fig(fig, "fig01_circuit_cost")


def fig_circuit_diagrams(d1):
    inst = d1["instances"]["5v"]
    qc = orc.grover(3, 1, "noancilla", ["101"], barriers=True)
    fig = qc.draw("mpl", fold=-1, style={"name": "clifford", "fontsize": 11})
    fig.savefig(FIG / "fig00a_grover_n3_circuit.pdf", bbox_inches="tight")
    fig.savefig(FIG / "fig00a_grover_n3_circuit.png", dpi=300, bbox_inches="tight")
    plt.close(fig)
    qc = orc.grover(5, 1, "noancilla", inst["solutions"], inst["clauses"], "A", barriers=True)
    fig = qc.draw("mpl", fold=40, style={"name": "clifford", "fontsize": 11})
    fig.savefig(FIG / "fig00b_ksat5_oracleA_circuit.pdf", bbox_inches="tight")
    fig.savefig(FIG / "fig00b_ksat5_oracleA_circuit.png", dpi=300, bbox_inches="tight")
    plt.close(fig)


def fig_baseline(d2):
    rows = d2["rows"]
    fig, (a, b) = plt.subplots(1, 2, figsize=(DOUBLE, 2.4), gridspec_kw={"width_ratios": [1.5, 1]})
    for kind, color, mk in (("k=1", "#2a78d6", "o"), ("k*", "#4a3aa7", "s")):
        rr = [r for r in rows if (r["k"] == 1 if kind == "k=1" else r["k"] == r["k_opt"])]
        if kind == "k*":
            rr = [r for r in rows if r["k"] == r["k_opt"]]
        ns = [r["n"] for r in rr]
        nn = np.linspace(2, 10, 200)
        th = [orc.p_theory(x, 1, 1) if kind == "k=1" else None for x in nn]
        if kind == "k=1":
            a.plot(nn, th, "-", color=color, lw=1, alpha=0.35)
        a.plot(ns, [r["p_theory"] for r in rr], "-", color=color, lw=1, alpha=0.6)
        a.errorbar(ns, [r["p_mean"] for r in rr], [r["p_std"] for r in rr], fmt=mk, color=color, mec="white",
                   mew=0.6, capsize=2, label=f"Simulator, {'$k=1$' if kind == 'k=1' else '$k^*$'}")
    a.plot([], [], "-", color=MUTED, lw=1, label=r"Theory $\sin^2((2k+1)\theta)$")
    a.plot(range(2, 11), [2**-n for n in range(2, 11)], ":", color=MUTED, lw=1, label=r"Random $2^{-n}$")
    a.set(xlabel=r"Qubits $n$", ylabel="P(marked state)", ylim=(-0.03, 1.08), xticks=range(2, 11))
    a.legend(loc="center right", fontsize=6.5)
    panel(a, "a")
    for kind, color, mk in (("k=1", "#2a78d6", "o"), ("k*", "#4a3aa7", "s")):
        rr = [r for r in rows if (r["k"] == 1 if kind == "k=1" else r["k"] == r["k_opt"])]
        b.semilogy([r["n"] for r in rr], [1e3 * r["sim_time_per_circuit_s"] for r in rr], mk + "-", color=color,
                   mec="white", mew=0.6, label=r"$k=1$" if kind == "k=1" else r"$k^*$")
    b.set(xlabel=r"Qubits $n$", ylabel="Simulator time per circuit (ms)", xticks=range(2, 11, 2))
    b.grid(True, which="major", axis="both")
    b.legend(loc="upper left")
    panel(b, "b")
    fig.tight_layout(w_pad=2)
    save_fig(fig, "fig02_simulator_baseline")


# ============================================================================ Stage B / C
def sources():
    out = {}
    for name in ("fake_kingston", "fake_marrakesh", "ibm_kingston", "ibm_marrakesh"):
        d = load(f"source_{name}.json")
        if d:
            out[name] = d
    return out


def rows_of(src, step=None, method=None):
    return [r for r in src["rows"] if (step is None or r["step"] == step) and (method is None or r["method"] == method)]


def stage_b(report, S):
    report.append("## Stage B — Hardware runs\n")
    hw = [s for s in S if is_hw(s)]
    if not hw:
        report.append("> **Hardware not yet run.** Every Stage B number below comes from the Step 3 noise-model "
                      "predictions (FakeKingston, FakeMarrakesh), so these are *predicted* values. After "
                      "`python study.py submit` and `collect`, rerunning `python study.py analyze` adds the QPU "
                      "columns next to them.\n")
    # Step 4 calibration
    rows = []
    for s, d in S.items():
        c = d["calibration"]
        for scope in ("device", "used"):
            x = c[scope]
            rows.append([src_label(s), c.get("calibration_date") or "–", "all qubits" if scope == "device"
                         else f"{len(c['used_qubits'])} used", f3(x["cz_error_median"]),
                         f3(x["readout_error_median"]), f"{x['t1_us_median']:.0f}" if x["t1_us_median"] else "–",
                         f"{x['t2_us_median']:.0f}" if x["t2_us_median"] else "–"])
    report.append("### Step 4: device calibration\n")
    report.append(write_table("tab_step4_calibration", ["Source", "Calibration date", "Qubits", "CZ error (median)",
                                                        "Readout error (median)", "T1 (µs)", "T2 (µs)"], rows,
                              "Device calibration (medians over all qubits and over the qubits the circuits use)",
                              "tab:calibration", "lllrrrr"))
    step5(report, S)
    step6(report, S)
    step7(report, S)
    step8(report, S)
    opt(report, S)


def _s5_summary(src):
    """{(instance, method): dict(p=[reps], ci, hell, cost)}"""
    out = {}
    for r in rows_of(src, "s5"):
        d = out.setdefault((r["instance"], r["method"]), {"p": [], "ci": [], "hell": [], "cost": [], "ptheory":
                                                           r["p_theory"], "n": r["n"]})
        d["p"].append(r["p"]); d["hell"].append(r["hellinger"]); d["cost"].append(r["est_qpu_s"])
        if r["ci95"]:
            d["ci"].append(r["ci95"])
    return out


def step5(report, S):
    report.append("### Step 5: error mitigation on K-SAT (Oracle A, k = 1, 2 repetitions)\n")
    rows = []
    for s, d in S.items():
        summ = _s5_summary(d)
        for inst in ("5v", "6v"):
            base = np.mean(summ[(inst, "none")]["p"])
            for t in TECH:
                if (inst, t) not in summ:
                    continue
                x = summ[(inst, t)]
                p = np.mean(x["p"])
                lo = min(c[0] for c in x["ci"]) if x["ci"] else None
                hi = max(c[1] for c in x["ci"]) if x["ci"] else None
                rows.append([src_label(s), inst, TECH_LABEL[t], f"{p:.3f}" + (f" [{lo:.3f}, {hi:.3f}]" if lo else ""),
                             f"{p - base:+.3f}", f"{np.mean(x['hell']):.3f}", f"{np.mean(x['cost']):.1f}",
                             f"{np.mean(x['cost']) / np.mean(summ[(inst, 'none')]['cost']):.1f}×"])
    report.append(write_table("tab_II_mitigation", ["Source", "Instance", "Technique", "P(solution) [95% CI]",
                                                    "Gain vs none", "Hellinger", "QPU cost (s)", "Cost ratio"], rows,
                              "Table II: K-SAT success probability per error-mitigation technique "
                              "(ideal: 5v 0.646, 6v 0.371)", "tab:II", "lllrrrrr"))
    fig_mitigation(S)


def fig_mitigation(S):
    fig, axes = plt.subplots(2, 1, figsize=(DOUBLE, 4.6), sharex=True)
    srcs = list(S)
    w = 0.8 / len(srcs)
    for ax, inst, letter in zip(axes, ("5v", "6v"), "ab"):
        ideal = None
        for j, s in enumerate(srcs):
            summ = _s5_summary(S[s])
            st = src_style(s)
            for i, t in enumerate(TECH):
                if (inst, t) not in summ:
                    continue
                x = summ[(inst, t)]
                ideal = x["ptheory"]
                p = float(np.mean(x["p"]))
                xpos = i + (j - (len(srcs) - 1) / 2) * w
                ax.bar(xpos, p, w * 0.9, color=st["color"], alpha=1 if is_hw(s) else 0.85, hatch=st["hatch"],
                       edgecolor="white", linewidth=0.4)
                if x["ci"]:
                    lo, hi = min(c[0] for c in x["ci"]), max(c[1] for c in x["ci"])
                    ax.plot([xpos, xpos], [lo, hi], color=INK, lw=0.7)
                ax.text(xpos, p + 0.015, f"{p:.2f}", ha="center", va="bottom", fontsize=5.4, color=INK2, rotation=90)
        n = 5 if inst == "5v" else 6
        ax.axhline(ideal, color=INK, lw=1, ls="-", zorder=0.5)
        ax.text(len(TECH) - 0.45, ideal, " ideal", va="center", fontsize=6.5, color=INK)
        ax.axhline(3 / 2**n, color=MUTED, lw=1, ls=":", zorder=0.5)
        ax.text(len(TECH) - 0.45, 3 / 2**n, " random", va="center", fontsize=6.5, color=MUTED)
        ax.set(ylabel="P(solution)", ylim=(0, max(ideal * 1.25, 0.5)), xlim=(-0.6, len(TECH) - 0.4))
        cnf = {"5v": "5 variables, 6 clauses", "6v": "6 variables, 7 clauses"}[inst]
        ax.set_title(f"{inst[0]}-variable K-SAT ({cnf}), Oracle A, $k=1$", loc="left")
        panel(ax, letter, -0.07)
    axes[-1].set_xticks(range(len(TECH)))
    axes[-1].set_xticklabels([TECH_LABEL[t] for t in TECH])
    handles = [Patch(facecolor=src_style(s)["color"], hatch=src_style(s)["hatch"], edgecolor="white",
                     alpha=1 if is_hw(s) else 0.85, label=src_label(s)) for s in srcs]
    handles.append(Line2D([], [], color=INK, lw=0.7, label="95% bootstrap CI"))
    fig.legend(handles=handles, loc="upper center", ncol=len(handles), bbox_to_anchor=(0.5, 1.01))
    fig.tight_layout(rect=(0, 0, 1, 0.96), h_pad=1.2)
    save_fig(fig, "fig03_mitigation")


def step6(report, S):
    report.append("### Step 6: K-SAT search on hardware (Oracle A, full distributions)\n")
    rows = []
    for s, d in S.items():
        for r in rows_of(d, "s6"):
            top = sorted(r["dist"].items(), key=lambda kv: -kv[1])[:3]
            rows.append([src_label(s), r["instance"], r["k"], f"{r['p_theory']:.3f}", f"{r['p']:.3f}",
                         f"{r['hellinger']:.3f}", ", ".join(b for b, _ in top),
                         sum(1 for b, _ in top if b in r["marked"])])
    report.append(write_table("tab_step6_ksat", ["Source", "Instance", "k", "P ideal", "P(solution)", "Hellinger",
                                                 "Top-3 outcomes", "Solutions in top 3"], rows,
                              "K-SAT search: success probability and most frequent bitstrings", "tab:ksat",
                              "llrrrrlr"))
    fig_distributions(S)


def fig_distributions(S):
    srcs = list(S)
    any_src = next(iter(S.values()))
    cases = [(r["instance"], r["k"]) for r in rows_of(any_src, "s6")]
    fig, axes = plt.subplots(len(cases), 1, figsize=(DOUBLE, 1.75 * len(cases)))
    for ax, (inst, k), letter in zip(axes, cases, "abcdefgh"):
        r0 = next(r for r in rows_of(any_src, "s6") if r["instance"] == inst and r["k"] == k)
        n = r0["n"]
        keys = [format(i, f"0{n}b") for i in range(2**n)]
        xs = np.arange(len(keys))
        for x, b in zip(xs, keys):
            if b in r0["marked"]:
                ax.axvspan(x - 0.5, x + 0.5, color="#1baf7a", alpha=0.13, lw=0)
        ax.bar(xs, [r0["ideal"].get(b, 0) for b in keys], 0.82, color="#d9d7d0", label="Ideal")
        for j, s in enumerate(srcs):
            r = next(x for x in rows_of(S[s], "s6") if x["instance"] == inst and x["k"] == k)
            st = src_style(s)
            off = (j - (len(srcs) - 1) / 2) * 0.22
            ax.plot(xs + off, [r["dist"].get(b, 0) for b in keys], "o", ms=2.6 if n == 6 else 3.2,
                    color=st["color"], mfc=st["mfc"], mew=0.8, label=src_label(s))
        ax.set_xticks(xs)
        ax.set_xticklabels(keys, rotation=90, fontsize=4.3 if n == 6 else 5.2, family="monospace")
        for t, b in zip(ax.get_xticklabels(), keys):
            if b in r0["marked"]:
                t.set_color("#0d7a52"); t.set_fontweight("bold")
        ax.set_xlim(-0.7, len(keys) - 0.3)
        ax.set_ylabel("Probability")
        ax.set_title(f"{n}-variable K-SAT, $k={k}$ (ideal P = {r0['p_theory']:.3f}); solutions shaded", loc="left")
        panel(ax, letter, -0.06)
    h, l = axes[0].get_legend_handles_labels()
    h.append(Patch(color="#1baf7a", alpha=0.25, label="Solution states")); l.append("Solution states")
    fig.legend(h, l, loc="upper center", ncol=len(h), bbox_to_anchor=(0.5, 1.01))
    fig.tight_layout(rect=(0, 0, 1, 0.975), h_pad=0.8)
    save_fig(fig, "fig04_ksat_distributions")


def step7(report, S):
    report.append("### Step 7: iteration sweep (n = 3, 4)\n")
    rows = []
    for s, d in S.items():
        for n in (3, 4):
            rr = sorted([r for r in rows_of(d, "s7") if r["n"] == n], key=lambda r: r["k"])
            best = max(rr, key=lambda r: r["p"])
            rows.append([src_label(s), n] + [f"{r['p']:.3f}" for r in rr] + [best["k"], orc.k_opt(n, 1)])
    report.append(write_table("tab_step7_sweep", ["Source", "n", "k=0", "k=1", "k=2", "k=3", "best k (measured)",
                                                  "k* (theory)"], rows,
                              "Iteration sweep: P(marked) against the number of Grover iterations",
                              "tab:sweep", "lrrrrrrr"))
    fig, axes = plt.subplots(1, 2, figsize=(DOUBLE, 2.3), sharey=True)
    for ax, n, letter in zip(axes, (3, 4), "ab"):
        kk = np.linspace(0, 3.2, 300)
        ax.plot(kk, [orc.p_theory(n, 1, k) for k in kk], "-", color=INK, lw=1, alpha=0.35)
        ax.plot(range(4), [orc.p_theory(n, 1, k) for k in range(4)], "o", color=INK, ms=4, label="Theory")
        for s, d in S.items():
            rr = sorted([r for r in rows_of(d, "s7") if r["n"] == n], key=lambda r: r["k"])
            st = src_style(s)
            ax.errorbar([r["k"] for r in rr], [r["p"] for r in rr],
                        yerr=[[r["p"] - r["ci95"][0] for r in rr], [r["ci95"][1] - r["p"] for r in rr]],
                        fmt="s" + st["ls"], color=st["color"], mfc=st["mfc"], mew=0.9, capsize=1.5, lw=1.2,
                        label=src_label(s))
        ax.axhline(2**-n, color=MUTED, ls=":", lw=1)
        ax.text(3.15, 2**-n, "random", fontsize=6.3, color=MUTED, va="bottom", ha="right")
        ax.set(xlabel="Grover iterations $k$", xticks=range(4), ylim=(0, 1.05),
               title=f"$n={n}$ ($k^*={orc.k_opt(n, 1)}$)")
        ax.title.set_ha("left"); ax.title.set_position((0, 1))
        panel(ax, letter, -0.1)
    axes[0].set_ylabel("P(marked state)")
    axes[1].legend(loc="upper right")
    fig.tight_layout(w_pad=1.5)
    save_fig(fig, "fig05_iteration_sweep")


def step8(report, S):
    report.append("### Step 8: Grover scaling (n = 2–7, 3 marked states each)\n")
    rows = []
    for s, d in S.items():
        for n in range(2, 8):
            for k in sorted({r["k"] for r in rows_of(d, "s8") if r["n"] == n}):
                rr = [r for r in rows_of(d, "s8") if r["n"] == n and r["k"] == k]
                ps = [r["p"] for r in rr]
                rows.append([src_label(s), n, k, f"{orc.p_theory(n, 1, k):.3f}",
                             f"{np.mean(ps):.3f} ± {np.std(ps, ddof=1) if len(ps) > 1 else 0:.3f}",
                             f"{2 ** -n:.3f}", int(np.mean([r["cz"] for r in rr])),
                             f"{np.mean([r['hellinger'] for r in rr]):.3f}"])
    report.append(write_table("tab_III_scaling", ["Source", "n", "k", "P theory", "P measured (mean ± sd, 3 states)",
                                                  "Random", "CZ gates", "Hellinger"], rows,
                              "Table III: Grover scaling with the number of qubits", "tab:III", "lrrrrrrr"))


def opt(report, S):
    rows = []
    for s, d in S.items():
        for inst in ("5v", "6v"):
            a = [r for r in rows_of(d, "s5", "none") if r["instance"] == inst]
            b = [r for r in rows_of(d, "opt") if r["instance"] == inst]
            if a and b:
                rows.append([src_label(s), inst, a[0]["cz"], f"{np.mean([r['p'] for r in a]):.3f}", b[0]["cz"],
                             f"{np.mean([r['p'] for r in b]):.3f}",
                             f"{np.mean([r['p'] for r in b]) - np.mean([r['p'] for r in a]):+.3f}"])
    if rows:
        report.append("### Optional: best Step-1 construction on hardware\n")
        report.append(write_table("tab_opt_construction", ["Source", "Instance", "CZ (no ancilla)", "P (no ancilla)",
                                                           "CZ (relative-phase V-chain)", "P (relative-phase)",
                                                           "Gain"], rows,
                                  "Compilation choice versus error mitigation (Oracle A, k = 1, no mitigation)",
                                  "tab:opt", "llrrrrr"))


# ============================================================================ Stage C
def step9(report, S):
    report.append("## Stage C — Analysis\n\n### Step 9: noise model against hardware\n")
    pairs = [(f"fake_{d}", f"ibm_{d}") for d in DEV_COLOR if f"fake_{d}" in S and f"ibm_{d}" in S]
    note = ""
    if not pairs and "fake_kingston" in S and "fake_marrakesh" in S:
        pairs = [("fake_kingston", "fake_marrakesh")]
        note = ("No hardware data yet: this compares the two noise models with each other, which shows how much "
                "the predictions depend on the device. With hardware data, each model is compared with its own QPU.")
    rows = []
    fig, ax = plt.subplots(figsize=(SINGLE, 3.1))
    ax.plot([0, 1], [0, 1], "-", color=MUTED, lw=0.8)
    ax.fill_between([0, 1], [-0.05, 0.95], [0.05, 1.05], color=GRID, alpha=0.6, lw=0, label="±0.05")
    for a, b in pairs:
        A = {r["id"]: r for r in S[a]["rows"]}
        B = {r["id"]: r for r in S[b]["rows"]}
        ids = [i for i in A if i in B]
        x = np.array([A[i]["p"] for i in ids]); y = np.array([B[i]["p"] for i in ids])
        mae, bias = float(np.mean(np.abs(y - x))), float(np.mean(y - x))
        rmse, r = float(np.sqrt(np.mean((y - x) ** 2))), float(np.corrcoef(x, y)[0, 1])
        rows.append([f"{src_label(a)} → {src_label(b)}", len(ids), f"{mae:.3f}", f"{rmse:.3f}", f"{bias:+.3f}",
                     f"{r:.3f}"])
        for step, mk in (("s5", "o"), ("s6", "D"), ("s7", "^"), ("s8", "s"), ("opt", "P")):
            sel = [k for k, i in enumerate(ids) if A[i]["step"] == step]
            if sel:
                ax.plot(x[sel], y[sel], mk, ms=3.6, color=DEV_COLOR[dev_of(b)], mec="white", mew=0.4, alpha=0.9,
                        label={"s5": "Step 5", "s6": "Step 6", "s7": "Step 7", "s8": "Step 8",
                               "opt": "Construction"}[step])
        ax.set_xlabel(f"{src_label(a)}: P(success)")
        ax.set_ylabel(f"{src_label(b)}: P(success)")
    ax.set(xlim=(0, 1), ylim=(0, 1), aspect="equal")
    ax.grid(True, axis="both")
    ax.legend(loc="upper left", fontsize=6.2)
    fig.tight_layout()
    save_fig(fig, "fig07_model_vs_hardware")
    if note:
        report.append(f"> {note}\n")
    report.append(write_table("tab_step9_model_accuracy", ["Comparison", "Circuits", "MAE", "RMSE", "Bias",
                                                           "Pearson r"], rows,
                              "Accuracy of the noise-model prediction of P(success)", "tab:model", "lrrrrr"))


def fit_F(rows):
    """Least-squares F in P = P_ideal F^g + (1 - F^g)/2^n over unmitigated Grover runs."""
    data = [(r["p"], r["p_theory"], r["cz"], r["n"]) for r in rows]

    def loss(F):
        return sum((p - (pi * F**g + (1 - F**g) / 2**n)) ** 2 for p, pi, g, n in data)

    res = minimize_scalar(loss, bounds=(0.9, 0.99999), method="bounded")
    rng = np.random.default_rng(0)
    boot = []
    for _ in range(300):
        smp = [data[i] for i in rng.integers(0, len(data), len(data))]
        boot.append(minimize_scalar(lambda F: sum((p - (pi * F**g + (1 - F**g) / 2**n)) ** 2
                                                  for p, pi, g, n in smp), bounds=(0.9, 0.99999),
                                    method="bounded").x)
    return float(res.x), [float(np.percentile(boot, 2.5)), float(np.percentile(boot, 97.5))]


def step10(report, S, d1):
    report.append("### Step 10: noise-scaling model\n")
    rows, fits = [], {}
    grover_cz = {}
    if d1:
        for v in orc.VARIANTS:
            rr = [r for r in d1["rows"] if r["circuit"].startswith("Grover") and r["variant"] == v]
            grover_cz[v] = ([r["n_vars"] for r in rr], [r["cz_kingston"] for r in rr])
    for s, d in S.items():
        rr = rows_of(d, "s7") + rows_of(d, "s8")
        F, ci = fit_F(rr)
        fits[s] = F
        e_cal = d["calibration"]["used"]["cz_error_median"] or d["calibration"]["device"]["cz_error_median"]
        g_rand = math.log(0.01) / math.log(F)
        n_rand = {}
        for v, (ns, cz) in grover_cz.items():  # first n where one iteration keeps <1% of the signal
            slope, icpt = np.polyfit(ns[-4:], np.log(cz[-4:]), 1)
            n_rand[v] = next((n for n in range(2, 60) if (cz[ns.index(n)] if n in ns else math.exp(icpt + slope * n))
                              >= g_rand), None)
        rows.append([src_label(s), f"{F:.5f} [{ci[0]:.5f}, {ci[1]:.5f}]", f"{1 - F:.2e}", f"{e_cal:.2e}",
                     f"{(1 - F) / e_cal:.1f}×", f"{g_rand:.0f}", n_rand.get("noancilla"), n_rand.get("vchain_rtof")])
    report.append(write_table("tab_step10_noise_fit", ["Source", "Effective CZ fidelity F [95% CI]", "1 − F",
                                                       "CZ error (calibration)", "Ratio", "CZ gates to random (F^g=1%)",
                                                       "n at random (no ancilla)", "n at random (rel.-phase)"],
                              rows, "Noise-scaling fit P = P_ideal F^g + (1 − F^g)/2^n (g = CZ count)",
                              "tab:fit", "lrrrrrrr"))
    # figure: scaling
    fig, (a, b) = plt.subplots(1, 2, figsize=(DOUBLE, 2.5))
    ns = list(range(2, 8))
    a.plot(ns, [orc.p_theory(n, 1, 1) for n in ns], "-o", color=INK, ms=3.5, lw=1, label="Theory ($k=1$)")
    a.plot(ns, [2**-n for n in ns], ":", color=MUTED, lw=1, label=r"Random $2^{-n}$")
    for s, d in S.items():
        st = src_style(s)
        rr = [r for r in rows_of(d, "s8") if r["k"] == 1]
        means = [np.mean([r["p"] for r in rr if r["n"] == n]) for n in ns]
        sds = [np.std([r["p"] for r in rr if r["n"] == n], ddof=1) for n in ns]
        a.errorbar(ns, means, sds, fmt="s" + st["ls"], color=st["color"], mfc=st["mfc"], mew=0.9, capsize=1.5,
                   lw=1.2, label=src_label(s))
        g = np.array([r["cz"] for r in rr]); p = np.array([r["p"] for r in rr])
        b.plot(g, p, "s", color=st["color"], mfc=st["mfc"], mew=0.8, ms=3.5, label=src_label(s))
        F = fits[s]
        gg = np.logspace(0, 3.3, 200)
        for n in ns:
            pi = orc.p_theory(n, 1, 1)
            sel = [r["cz"] for r in rr if r["n"] == n]
            if sel:
                g0 = np.mean(sel)
                b.plot([g0], [pi * F**g0 + (1 - F**g0) / 2**n], "_", color=st["color"], ms=9, mew=1.4)
        b.plot(gg, F**gg, st["ls"], color=st["color"], lw=1, alpha=0.8)
    b.plot([], [], "-", color=INK2, lw=1, label=r"Fitted signal $F^{g}$")
    a.set(xlabel=r"Qubits $n$", ylabel="P(marked state), $k=1$", ylim=(0, 1.05), xticks=ns)
    a.legend(loc="upper right", fontsize=6.3)
    panel(a, "a")
    b.set_xscale("log")
    b.set(xlabel="CZ gates $g$", ylabel="P(marked) / signal $F^g$", ylim=(0, 1.05), xlim=(1, 2e3))
    b.grid(True, which="major", axis="both")
    b.legend(loc="lower left", fontsize=6.3)
    panel(b, "b")
    fig.tight_layout(w_pad=2)
    save_fig(fig, "fig06_scaling")
    return fits


def step11(report, S):
    report.append("### Step 11: K-SAT time-to-solution\n")
    rows = []
    data = {}
    for s, d in S.items():
        for inst in ("5v", "6v"):
            n = 5 if inst == "5v" else 6
            rand = 2**n / 3
            for t in TECH:
                rr = [r for r in rows_of(d, "s5", t) if r["instance"] == inst]
                if not rr:
                    continue
                p = np.mean([r["p_clause_check"] for r in rr])
                shots = 1 / p if p > 0 else float("inf")
                data[(s, inst, t)] = (shots, rand)
                rows.append([src_label(s), inst, TECH_LABEL[t], f"{p:.3f}", f"{shots:.2f}", f"{rand:.2f}",
                             f"{rand / shots:.2f}×"])
            for r in rows_of(d, "s6") + [x for x in rows_of(d, "opt") if x["rep"] == 0]:
                if r["instance"] == inst:
                    lbl = f"k={r['k']}" if r["step"] == "s6" else "rel.-phase, k=1"
                    rows.append([src_label(s), inst, f"none ({lbl})", f"{r['p_clause_check']:.3f}",
                                 f"{1 / r['p_clause_check']:.2f}", f"{rand:.2f}", f"{rand * r['p_clause_check']:.2f}×"])
    report.append("Every measured bitstring is checked against the CNF clauses. The expected number of shots to "
                  "the first solution is 1/P, compared with 2ⁿ/3 for random guessing (3 solutions).\n")
    report.append(write_table("tab_step11_tts", ["Source", "Instance", "Technique", "P(clauses satisfied)",
                                                 "Expected shots 1/P", "Random 2ⁿ/3", "Speed-up"], rows,
                              "K-SAT time-to-solution", "tab:tts", "lllrrrr"))
    fig, axes = plt.subplots(1, 2, figsize=(DOUBLE, 2.3), sharey=False)
    srcs = list(S)
    w = 0.8 / len(srcs)
    for ax, inst, letter in zip(axes, ("5v", "6v"), "ab"):
        n = 5 if inst == "5v" else 6
        for j, s in enumerate(srcs):
            st = src_style(s)
            xs = [i + (j - (len(srcs) - 1) / 2) * w for i in range(len(TECH))]
            ys = [data[(s, inst, t)][0] for t in TECH]
            ax.bar(xs, ys, w * 0.9, color=st["color"], hatch=st["hatch"], alpha=1 if is_hw(s) else 0.85,
                   edgecolor="white", linewidth=0.4, label=src_label(s))
        ax.axhline(2**n / 3, color=MUTED, ls=":", lw=1)
        ax.text(len(TECH) - 0.5, 2**n / 3, "random", fontsize=6.3, color=MUTED, va="bottom", ha="right")
        ax.axhline(1 / orc.p_theory(n, 3, 1), color=INK, lw=1)
        ax.text(len(TECH) - 0.5, 1 / orc.p_theory(n, 3, 1), "ideal Grover", fontsize=6.3, color=INK, va="bottom",
                ha="right")
        ax.set_xticks(range(len(TECH)))
        ax.set_xticklabels([TECH_LABEL[t] for t in TECH], rotation=30, ha="right")
        ax.set(ylabel="Expected shots to a solution", title=f"{n}-variable K-SAT")
        ax.title.set_ha("left"); ax.title.set_position((0, 1))
        panel(ax, letter, -0.13)
    axes[0].legend(loc="upper left", fontsize=6.2)
    fig.tight_layout(w_pad=2)
    save_fig(fig, "fig08_time_to_solution")


def step12(report, S):
    report.append("### Step 12: statistics and cost–benefit\n")
    report.append("95% confidence intervals are percentile bootstraps (1000 resamples of the shots for unmitigated "
                  "runs, 200 for mitigated runs, which recompute the whole mitigation from resampled counts). "
                  "Hellinger fidelity compares each output distribution with the exact one.\n")
    rows, pts = [], []
    for s, d in S.items():
        summ = _s5_summary(d)
        for t in TECH:
            gains, dh, costs, ratios = [], [], [], []
            for inst in ("5v", "6v"):
                if (inst, t) not in summ:
                    continue
                x, b = summ[(inst, t)], summ[(inst, "none")]
                gains.append(np.mean(x["p"]) - np.mean(b["p"]))
                dh.append(np.mean(x["hell"]) - np.mean(b["hell"]))
                costs.append(np.mean(x["cost"]))
                ratios.append(np.mean(x["cost"]) / np.mean(b["cost"]))
            if not gains:
                continue
            g, c = float(np.mean(gains)), float(np.mean(costs))
            extra = c - np.mean([np.mean(summ[(i, "none")]["cost"]) for i in ("5v", "6v")])
            pts.append((s, t, float(np.mean(ratios)), g))
            rows.append([src_label(s), TECH_LABEL[t], f"{g:+.3f}", f"{np.mean(dh):+.3f}", f"{c:.1f}",
                         f"{np.mean(ratios):.1f}×", "–" if t == "none" else f"{g / extra:+.4f}" if extra > 1e-9 else "–"])
    report.append(write_table("tab_step12_cost_benefit", ["Source", "Technique", "ΔP(solution)", "ΔHellinger",
                                                          "QPU cost per run (s)", "Cost ratio", "ΔP per extra second"],
                              rows, "Cost–benefit of each mitigation technique (average of both instances)",
                              "tab:cost", "llrrrrr"))
    fig, ax = plt.subplots(figsize=(SINGLE + 0.6, 2.8))
    ax.axhline(0, color=INK2, lw=0.8)
    markers = {"kingston": "o", "marrakesh": "s"}
    for s, t, ratio, g in pts:
        hw = is_hw(s)
        ax.plot(ratio, g, markers[dev_of(s)], ms=6.5, color=TECH_COLOR[t], mfc=TECH_COLOR[t] if hw else "white",
                mew=1.3, mec=TECH_COLOR[t])
        ax.annotate(TECH_LABEL[t], (ratio, g), xytext=(5, 2), textcoords="offset points", fontsize=6.2,
                    color=INK2)
    ax.set_xscale("log")
    ax.set(xlabel="QPU cost relative to no mitigation", ylabel=r"Gain $\Delta P$(solution)")
    ax.grid(True, axis="both")
    handles = [Line2D([], [], marker=markers[dv], ls="", color=INK2, mfc="white", label=f"{dv.capitalize()}")
               for dv in markers if any(dev_of(s) == dv for s in S)]
    handles += [Line2D([], [], marker="o", ls="", color=INK2, mfc=INK2, label="filled = QPU"),
                Line2D([], [], marker="o", ls="", color=INK2, mfc="white", label="hollow = model")]
    ax.legend(handles=handles, loc="best", fontsize=6.2)
    fig.tight_layout()
    save_fig(fig, "fig09_cost_benefit")
    return pts


def recommendations(report, S, pts, fits):
    report.append("### Practical recommendations\n")
    lines = []
    for s in S:
        cand = [(g, r, t) for (src, t, r, g) in pts if src == s and t != "none"]
        if not cand:
            continue
        best = max(cand)
        cheap = [c for c in cand if c[1] <= 1.2]
        best_cheap = max(cheap) if cheap else None
        per_sec = max(cand, key=lambda c: c[0] / max(c[1] - 1, 0.05))
        lines.append(f"- **{src_label(s)}**: largest gain from **{TECH_LABEL[best[2]]}** (ΔP = {best[0]:+.3f} at "
                     f"{best[1]:.1f}× QPU cost); best value per QPU second **{TECH_LABEL[per_sec[2]]}** "
                     f"({per_sec[0]:+.3f})"
                     + (f"; best at ≤1.2× cost **{TECH_LABEL[best_cheap[2]]}** ({best_cheap[0]:+.3f})."
                        if best_cheap else "."))
    for s, F in fits.items():
        lines.append(f"- {src_label(s)}: effective CZ fidelity {F:.4f}. A circuit keeps only 1% of its ideal "
                     f"signal after ≈{math.log(0.01) / math.log(F):.0f} CZ gates, so compilation (fewer CZ) matters "
                     "more than mitigation once circuits exceed a few hundred CZ gates.")
    report.append("\n".join(lines) + "\n")


# ============================================================================ main
def run():
    OUT.mkdir(parents=True, exist_ok=True)
    FIG.mkdir(parents=True, exist_ok=True)
    report = ["# Grover search and K-SAT on IBM Heron: full study\n",
              "Every number is generated by `Code/study.py` and `Code/study_analysis.py`. The tables are also in "
              "`Results/study/*.tex` (LaTeX) and `*.csv`, and the figures are in `Figures/study/` (PDF + PNG). "
              "*Model* = IBM noise model (FakeKingston/FakeMarrakesh), *QPU* = real hardware.\n"]
    stage_a(report)
    S = sources()
    if S:
        stage_b(report, S)
        step9(report, S)
        fits = step10(report, S, load("step1_design.json"))
        step11(report, S)
        pts = step12(report, S)
        recommendations(report, S, pts, fits)
    figs = sorted(p.name for p in FIG.glob("*.png"))
    report.append("## Figures\n\n" + "\n".join(f"![{f}](../../Figures/study/{f})" for f in figs) + "\n")
    (OUT / "REPORT.md").write_text("\n".join(report))
    print(f"wrote Results/study/REPORT.md, {len(list(OUT.glob('*.tex')))} LaTeX tables, {len(figs)} figures")


if __name__ == "__main__":
    run()
